import { test, expect } from "@playwright/test";

// Epic 7.4 — empirical proof that the Next static export boots inside a webview's
// constraints: a non-root mount AND a strict nonce CSP (no 'unsafe-eval', no
// 'unsafe-inline' for scripts). out/webview.html is generated by
// scripts/make-webview-html.mjs, mirroring the panel's prepareExportHtml
// transform. If a future build needed eval, or an inline script lost its nonce,
// the CSP would block it and these specs would fail.

// "Refused to …" is how Chromium reports a CSP block to the console.
const isCspViolation = (text: string): boolean => /Refused to|Content Security Policy/i.test(text);

test("the export boots under a strict nonce CSP with zero violations", async ({ page }) => {
  const violations: string[] = [];
  const errors: string[] = [];
  page.on("console", (m) => {
    if (m.type() === "error") {
      if (isCspViolation(m.text())) violations.push(m.text());
      else if (!/favicon/.test(m.text())) errors.push(m.text());
    }
  });
  page.on("pageerror", (e) => errors.push(e.message));

  await page.goto("webview.html");

  // Booted: Sigma painted a canvas and the header reports the node count — which
  // only happens after the inline hydration scripts and dynamic chunks all ran.
  await expect(page.locator("canvas").first()).toBeVisible();
  await expect(page.getByText(/\d[\d,]* nodes/).first()).toBeVisible();

  expect(violations).toEqual([]);
  expect(errors).toEqual([]);
});

test("the served webview.html carries the strict CSP and a mount <base>", async ({ request }) => {
  const html = await (await request.get("webview.html")).text();
  expect(html).toMatch(/Content-Security-Policy/);
  expect(html).toContain("script-src 'self' 'nonce-");
  expect(html).not.toContain("unsafe-eval");
  expect(html).toContain('<base href="./">');
  // Every script — inline hydration and external chunk — must carry the nonce.
  const scripts = html.match(/<script\b[^>]*>/g) ?? [];
  expect(scripts.length).toBeGreaterThan(0);
  expect(scripts.every((s) => s.includes('nonce="smoketestnonce"'))).toBe(true);
});
